### ISSUE TITLE
Migration/installation with artisan migrate

### ISSUE THREAD

**Issue by lion2486** [thekordy/ticketit#270]
Hello there and thank your your great job!
I installed your module and the installation was a charm. After that I would like to integrate with my whole system, change the default settings (I placed the ticketid.php config file) but I have some issues.

First when I am trying to migrate my project from empty one, I cannot do it because your modules initializes something using database, so I had to comment out the line added into config/app.php provider, in order to run the complete migration.

Second I uncomment the commented line and the /tickets are not working, I have to make /tickets-install process again, but I want all to be already set up and ready to use.

**Comment by lion2486** [comment]
Maybe The second part was my problem, I push the settings into the database and all works, but without the migration nothing works from php artisan.

**Comment by thekordy** [comment]
Thank you very much, would you please mention what error do you get?

**Comment by lion2486** [comment]
php artisan migrate
  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.migrations' doesn't exist (SQL: select \* from migrations)

  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.migrations' doesn't exist

And the log file:
```
[2016-11-10 16:28:13] local.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.migrations' doesn't exist' in C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:319
Stack trace:
#0 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php(319): PDO->prepare('select \* from m...')
#1 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php(644): Illuminate\Database\Connection->Illuminate\Database{closure}(Object(Illuminate\Database\MySqlConnection), 'select \* from m...', Array)
#2 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php(611): Illuminate\Database\Connection->runQueryCallback('select \* from m...', Array, Object(Closure))
#3 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php(324): Illuminate\Database\Connection->run('select \* from m...', Array, Object(Closure))
#4 [internal function]: Illuminate\Database\Connection->select('select \* from m...')
#5 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(296): call_user_func_array(Array, Array)
#6 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(216): Illuminate\Database\DatabaseManager->__call('select', Array)
#7 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(216): Illuminate\Database\DatabaseManager->select('select \* from m...')
#8 C:\Projects\my-project\vendor\kordy\ticketit\src\Controllers\InstallController.php(156): Illuminate\Support\Facades\Facade::__callStatic('select', Array)
#9 C:\Projects\my-project\vendor\kordy\ticketit\src\Controllers\InstallController.php(156): Illuminate\Support\Facades\DB::select('select \* from m...')
#10 C:\Projects\my-project\vendor\kordy\ticketit\src\TicketitServiceProvider.php(27): Kordy\Ticketit\Controllers\InstallController->inactiveMigrations()
#11 [internal function]: Kordy\Ticketit\TicketitServiceProvider->boot()
#12 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Container\Container.php(503): call_user_func_array(Array, Array)
#13 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(734): Illuminate\Container\Container->call(Array)
#14 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Kordy\Ticketit\TicketitServiceProvider))
#15 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation{closure}(Object(Kordy\Ticketit\TicketitServiceProvider), 22)
#16 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(718): array_walk(Array, Object(Closure))
#17 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#18 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#19 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#20 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#21 C:\Projects\my-project\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.migrations' doesn't exist (SQL: select \* from migrations)' in C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php:651
Stack trace:
#0 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php(611): Illuminate\Database\Connection->runQueryCallback('select \* from m...', Array, Object(Closure))
#1 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\Connection.php(324): Illuminate\Database\Connection->run('select \* from m...', Array, Object(Closure))
#2 [internal function]: Illuminate\Database\Connection->select('select \* from m...')
#3 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(296): call_user_func_array(Array, Array)
#4 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(216): Illuminate\Database\DatabaseManager->__call('select', Array)
#5 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(216): Illuminate\Database\DatabaseManager->select('select \* from m...')
#6 C:\Projects\my-project\vendor\kordy\ticketit\src\Controllers\InstallController.php(156): Illuminate\Support\Facades\Facade::__callStatic('select', Array)
#7 C:\Projects\my-project\vendor\kordy\ticketit\src\Controllers\InstallController.php(156): Illuminate\Support\Facades\DB::select('select \* from m...')
#8 C:\Projects\my-project\vendor\kordy\ticketit\src\TicketitServiceProvider.php(27): Kordy\Ticketit\Controllers\InstallController->inactiveMigrations()
#9 [internal function]: Kordy\Ticketit\TicketitServiceProvider->boot()
#10 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Container\Container.php(503): call_user_func_array(Array, Array)
#11 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(734): Illuminate\Container\Container->call(Array)
#12 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Kordy\Ticketit\TicketitServiceProvider))
#13 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation{closure}(Object(Kordy\Ticketit\TicketitServiceProvider), 22)
#14 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(718): array_walk(Array, Object(Closure))
#15 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\BootProviders.php(17): Illuminate\Foundation\Application->boot()
#16 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#17 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#18 C:\Projects\my-project\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#19 C:\Projects\my-project\artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}  

```

**Comment by thekordy** [comment]
Remove the TicketitServiceProvider from config/app.php, migrate, add it back

**Comment by lion2486** [comment]
I already to this, but I mentioned it here as there will be some fix for that, in order to make the whole project installable. I think that you could add a try-catch exception handling at this point and not rethrow this exception in order to let artitian-loader run. Thank you, I hope to be a easy part to fix and save time from others too!

**Comment by thekordy** [comment]
Thanks for the report, If you have a Pr to fix this, it'd be very appreciated.

**Comment by lion2486** [comment]
I added a try() to the whole boot() method and this catch statement
`catch(\Illuminate\Database\QueryException` $exception){
            //I think code 42S02 is for missing migration
            echo("There was a Query exception with message: \n" .
                $exception->getMessage() . "( code: " . $exception->getCode() . " ) \n" .
                "But maybe there was no migrations table, skipping error.");

```
    }`
```

**Comment by lion2486** [comment]
Also in many artisan commands I am getting the following error, and it's solving when I disable the package.
` [ErrorException]
  Undefined variable: migration_arr`

**Comment by balping** [comment]
Closing due to lack of activity.

If still an issue, please reopen.
