### ISSUE TITLE
have error php fatal in server

### ISSUE THREAD

**Issue by webineh** [thekordy/ticketit#414]
hi 
i install ticketit in localhost then move in server return error

```
Sat Nov 18 13:59:21.363433 2017] [:error] [pid 28594] [client 5.122.37.246:60104] PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /home/supportwe/domains/support.webineh.net/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
Stack trace:
#0 /home/supportwe/domains/support.webineh.net/vendor/laravel/framework/src/Illuminate/Container/Container.php(752): ReflectionClass->__construct('config')
#1 /home/supportwe/domains/support.webineh.net/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\\Container\\Container->build('config')
#2 /home/supportwe/domains/support.webineh.net/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\\Container\\Container->resolve('config', Array)
#3 /home/supportwe/domains/support.webineh.net/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\\Container\\Container->make('config', Array)
#4 /home/supportwe/domains/support.webineh.net/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(110): Illuminate\\Foundation\\Application->make('config', Arr in /home/supportwe/domains/support.webineh.net/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752
```

**Comment by balping** [comment]
Hello,

Something must be wrong with your laravel installation, this is not ticketit sepcific

**Comment by balping** [comment]
Closing due to lack of activity.
